# Generated by Django 5.0.6 on 2024-07-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myschool_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="name",
            field=models.CharField(default="Default Department", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="teachersubjectclass",
            constraint=models.UniqueConstraint(
                fields=("teacher", "subject", "class_assigned"),
                name="unique_teacher_subject_class",
            ),
        ),
    ]
