# Generated by Django 5.0.4 on 2024-07-08 14:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myschool_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprogress",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="myschool_app.lecturenote",
            ),
        ),
        migrations.RemoveField(
            model_name="video",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="video",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="date_assigned",
        ),
        migrations.RemoveField(
            model_name="lecturenote",
            name="date_uploaded",
        ),
        migrations.AddField(
            model_name="assignment",
            name="class_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myschool_app.class",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="upload_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="assignment",
            name="week",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="lecturenote",
            name="class_associated",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="myschool_app.class",
            ),
        ),
        migrations.AddField(
            model_name="lecturenote",
            name="description",
            field=models.TextField(default="Default description"),
        ),
        migrations.AddField(
            model_name="lecturenote",
            name="document_week",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="lecturenote",
            name="uploaded_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="lecturenote",
            name="week",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="description",
            field=models.TextField(default="Default description"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="lecturenote",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="lecturenote",
            name="file",
            field=models.FileField(upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="lecturenote",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="myschool_app.subject",
            ),
        ),
        migrations.AlterField(
            model_name="lecturenote",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="myschool_app.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="lecturenote",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
