# Generated by Django 5.0.6 on 2024-07-08 15:45

import myschool_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myschool_app", "0003_alter_lecturenote_class_associated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="classes",
        ),
        migrations.RemoveField(
            model_name="student",
            name="courses",
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                default=myschool_app.models.generate_unique_id,
                max_length=12,
                unique=True,
            ),
        ),
    ]
