# Generated by Django 5.0.6 on 2024-07-08 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myschool_app", "0005_alter_student_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="resources",
            field=models.URLField(
                blank=True, validators=[django.core.validators.URLValidator]
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="classes",
            field=models.ManyToManyField(
                related_name="teachers_classes", to="myschool_app.class"
            ),
        ),
    ]
