# Generated by Django 5.0.6 on 2024-07-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myschool_app", "0006_alter_class_resources_alter_teacher_classes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="new_teachers",
        ),
        migrations.RemoveField(
            model_name="class",
            name="teachers",
        ),
        migrations.RemoveField(
            model_name="teacherclass",
            name="school_class",
        ),
        migrations.AddField(
            model_name="teachersubjectclass",
            name="class_arm",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
